DELETE
FROM WorkshopExercise;
DELETE
FROM Workshops;
DELETE
FROM Workouts;
DELETE
FROM Exercises;
DELETE
FROM ExerciseCategory;
DELETE
FROM TrainingScheduleExercise;
DELETE
FROM TrainingSchedules;
DELETE
FROM Journeys;

ALTER TABLE WorkshopExercise
    AUTO_INCREMENT = 1;
ALTER TABLE Workshops
    AUTO_INCREMENT = 1;
ALTER TABLE Workouts
    AUTO_INCREMENT = 1;
ALTER TABLE Exercises
    AUTO_INCREMENT = 1;
ALTER TABLE ExerciseCategory
    AUTO_INCREMENT = 1;
ALTER TABLE TrainingScheduleExercise
    AUTO_INCREMENT = 1;
ALTER TABLE TrainingSchedules
    AUTO_INCREMENT = 1;
ALTER TABLE Journeys
    AUTO_INCREMENT = 1;


INSERT INTO ExerciseCategory
    (Name)
VALUES ('Benen'),
       ('Borst'),
       ('Buik'),
       ('Rug'),
       ('Armen'),
       ('Triceps'),
       ('Shouders'),
       ('Biceps'),
       ('Onderarmen'),
       ('Total workout'),
       ('Billen'),
       ('Taille'),
       ('Stretch');

INSERT INTO Workshops (Name)
VALUES ('Training 1'),
       ('Gym ball'),
       ('Core'),
       ('Powerbag'),
       ('Bosu'),
       ('RIP60'),
       ('Cable Cross'),
       ('Powerlifting'),
       ('Free weight');


INSERT INTO Exercises
    (Name, Description, ImagePath, CategoryId)
VALUES ('Air squat (eventueel met kettlebell)',
        'Ga met je voeten iets breder dan schouder breedte staan. Houd je borst recht omhoog en kijk recht vooruit. Laat je langzaam door je knieen zakken alsof je gaat zitten op een stoel. Leg bij het zakken je lichaamsgewicht op je hakken.Kom parallel met de grond (hoek van 90 graden en druk vervolgens met je hakken jezelf weer omhoog. Zorg ervoor dat je knieen niet op slot gaan wanneer je bovenin komt maar zorg wel voor een volledige heupstrekking.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/air_squat.png', 1),
       ('Push up',
        'Zet je handen op schouderbreedte op de vloer en je tenen tenen/knieen aan de grond. Je spant je buikspieren aan en je lichaam is een rechte lijn. Laat je langzaam naar beneden zakken, duw je ellebogen licht naar buiten. Je stopt net boven de vloer met je borst tussen de ellebogen. Vanuit deze positie duw je jezelf weer omhoog. De beweging komt vanuit je armen, de rest van je lichaam is stil.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/12.jpg', 2),
       ('Butterfly sit-up met med ball',
        'Je zit op de grond met je voetzolen tegen elkaar en je hakken zo dicht mogelijk bij je billen. De Medball houd je met twee handen vast. Je tikt met de medball de grond aan voor je tenen, hierna ga je rustig terug naar achter, je rug naar de vloer en je strekt je armen achter je hoofd. De med ball raakt de vloer opnieuw aan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/butterfly.png', 3),
       ('Deadlift met kettlebell',
        'Je staat rechtop met je voeten onder je heupen. Je hebt de kettlebell met twee handen vast, je armen zijn gestrekt. Je trekt je navel in en buigt met een rechte rug vanaf je heup naar voren. Je armen blijven gestrekt en bewegen dicht langs het lichaam. Vanuit je heup strek je weer uit terug naar de beginpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/deadlift_met_kettlebell.png', 4),
       ('Fireman pick up',
        'Leg de powerbag tussen je benen en pak hem met twee handen van de grond. Leg de powerbag in een beweging op je schouder. Leg de powerbag weer terug en herhaal de oefening nu met je andere schouder.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/fireman_pick_up.png', 1),
       ('Gym Ball push up',
        'Plaats je handen iets breder dan je schouders op de vloer en leg je onderbenen op de bal. Je staat nu als een rechte plank. Je buigt je ellebogen en brengt je borst naar de vloer. Heupen blijven recht. Duw jezelf weer op naar de plank.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/gym_ball_push_up.png', 2),
       ('Roll out',
        'Ga op je knieen voor de bal zitten. Plaats je handen en onderarmen op de bal. Zet je buikspieren op spanning door je knieen iets naar achter te zetten en je navel naar binnen te trekken. Rol nu de bal verder naar voren door je armen weg te duwen en hierna weer terug',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/roll_out.png', 3),
       ('Ball transfer',
        'Ga op je rug liggen. De Gym Ball is geklemd tussen je voeten. Trek je buikspieren aan, en je onderrug duw je met kracht in de mat. Benen en armen zijn gestrekt. Breng nu de bal met gestrekte benen omhoog, waar je hem ter hoogte van je navel doorgeeft aan je handen. Wanneer je lichaam weer gestrekt is (armen en benen blijven los van de grond) geef je de bal weer op dezelfde manier door aan je voeten.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/ball_tranfer.png', 3),
       ('Knee tuck',
        'Neem een plank positie aan, met je voeten op de bal, en je handen op de grond. Je navel is in en je heupen zijn recht. Langzaam trek je je knieen naar je borst. Probeer je lichaam verder zo stil mogelijk te houden. Daarna rol je met je benen over de bal terug naar de beginpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/knee_tuck.png', 3),
       ('Hip bridge',
        'Ga op je rug liggen met je voeten op de bal. Je benen zijn op ongeveer 90 graden gebogen. Leg je armen langs je lichaam en duw je heupen omhoog door druk te zetten op je benen. Alleen je armen, schouderbladen en hoofd rusten nog op de grond. Daarna laat je je heupen gecontroleerd weer zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/hip_bridge.png', 3),
       ('Single leg extension',
        'Ga zitten op de bal, je benen gebogen op ongeveer 90 graden. Je rug is recht, je buik op spanning. Zet je voeten plat op de grond. Rustig trek je een been los en strek deze parallel aan de grond uit. Houd vast. Daarna wissel je.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/single_leg_extention.png', 1),
       ('Back extension',
        'Ga met je buik op de Gym Ball liggen maak je rug bol. Kom nu rustig omhoog en maak je rug hol. Span je bilspieren aan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/back_extension.png', 4),
       ('Pivot bar',
        'Je pakt de stang met gestrekte armen vast en plaatst je voeten op heupbreedte. Laat de bar nu zo ver mogelijk naar links of rechts zakken en houd de heupen stil. Als de deelnemer niet verder kan dan draait de deelnemer de stang naar de andere kant.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/pivot_bar.png', 3),
       ('Ab Roller',
        'Ga op je knieen zitten en pak de barbell op schouderbreedte vast. Rol de barbell naar voren totdat je bijna de grond raakt. Op dit moment kom je weer omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/ab_roller.png', 3),
       ('The one hundred',
        'Breng je benen gestrekt omhoog tot ze in een hoek zijn van ongeveer 45 graden. Haal je schouders van de grond en strek de armen langs je lichaam. De armen worden dan als een pomp op en neer bewogen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/the_one_hundred.png', 3),
       ('Windshield wiper',
        'Ga plat op de grond liggen met de handen onder de billen. Strek je benen recht omhoog in een hoek van 90 graden. Vervolgens laat je beide benen gestrekt naar de zijkant zakken tot ze bijna de grond raken en breng ze dan weer terug om vervolgens de benen naar de andere kant te laten zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/windschield_wiper.png', 3),
       ('Plank knieen omhoog/omlaag- walking',
        'Ga in de plank positie liggen. Is dit op de knieen? Breng dan een knie zo hoog mogelijk omhoog en weer terug. Heb je de knieeen van de grond? Breng dan de knieen zover mogelijk onder het lichaam en weer terug. Als dit goed gaat maak dan een walking plank door middel van het naar voren brengen van de arm en het tegenovergestelde been. Dit kan ook uitgevoerd worden op de knieen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/plank_knees.png', 3),
       ('Pike-up',
        'Ga in de opdrukhouding staan. Breng je billen zo ver mogelijk omhoog met een rechte rug en gestrekte benen en zak vervolgens weer rustig terug. Vervolgens ga je in de opdrukhouding staan en spring je met 2 voeten tegelijk zo ver mogelijk naar je gezicht en weer terug.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/pike_up.png', 3),
       ('Powerbag Front Squat',
        'Plaats de Powerbag bij je sleutelbeen. Ga met je voeten iets breder dan schouderbreedte staan. Houd je borst recht omhoog en kijk voor je uit. Laat je langzaam door je knieen zakken, alsof je op een stoel gaat zitten. Leg bij het zakken je lichaamsgewicht op je hakken. Kom parallel met de grond (hoek van 90 graden) en druk vervolgens met je hakken jezelf weer omhoog. Zorg ervoor dat je knieen niet op slot gaan wanneer je bovenin komt, wel volledige heupstrekking.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_front_squat.png', 1),
       ('Powerbag Push Press',
        'Je voeten staan onder je heupen en je plaatst de Powerbag bij je sleutelbeen. Je zakt een klein stukje door je knieen en in de opwaartse beweging strek je je armen uit. Je eindigt met een volledige strekking van armen en heupen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_push_press.png', 4),
       ('Powerbag Goodmorning',
        'Plaats de Powerbag hoog op de bovenrug, onder de nek. Je voeten staan onder je heupen en je knieen zijn licht gebogen. Trek je navel in en span je buikspieren aan. Vanuit deze positie duw je je heupen naar achter en buig je met een rechte rug naar voren. Na de buiging ga je opnieuw met een rechte rug terug rechtop staan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_goodmorning.png', 4),
       ('Powerbag Push up',
        'Je plaatst je handen op de Powerbag en je knieen of tenen aan de grond. Je bovenlichaam is een rechte lijn. Je buigt je ellebogen en zakt rustig naar beneden tot een horizontale lijn. Je heupen raken de vloer niet aan. Vanuit hier duw je jezelf terug omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_push_up.png', 2),
       ('Powerbag around the world',
        'Beweeg de Powerbag met twee armen met een draaiende beweging om je hoofd. Je staat stabiel met je voeten onder je heupen, knieen licht gebogen en je core aangespannen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_around_the_world.png', 5),
       ('Powerbag Burpee',
        'Je begint staand met de Powerbag vast met gestrekt armen. Zet de Powerbag op de grond, spring/stap naar achter en maak een push- up. Spring/stap weer naar voren en kom terug naar de squat positie. Vervolgens ga je rechtop staan en in de opwaartse beweging strek je je armen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/powerbag_burpee.png', 5),
       ('Side to side bosu push up',
        'De bosu ligt met de platte kant naar beneden. Je plaatst je hand op de bosu en je andere hand op de grond. Handen staan op schouderbreedte. Plaatst tenen/knieen op de grond. Je lichaam is een rechte lijn. Buig je armen en breng je borst naar de vloer, ellebogen licht naar buiten. Duw jezelf terug omhoog. Wissel van hand op de bosu en herhaal.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/side_to_side_bosu_push_up.png', 2),
       ('Alternating bosu squat',
        'De bosu ligt met de platte kant naar beneden. Plaats een voet op de BOSU en de andere voet op de vloer, schouderbreedte. Breng je billen naar achter en kom parallel aan de vloer, hoek van 90 graden. Strek uit omhoog en wissel van been, mogelijk met sprong.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/alternating_bosu_squat.png', 1),
       ('Bosu plank +leg lift',
        'Plaats de Powerbag hoog op de bovenrug, onder de nek. Je voeten staan onder je heupen en je knieen zijn licht gebogen. Trek je navel in en span je buikspieren aan. Vanuit deze positie duw je je heupen naar achter en buig je met een rechte rug naar voren. Na de buiging ga je opnieuw met een rechte rug terug rechtop staan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bosu_plank_leg_lift.png', 1),
       ('Bosu hyper extension',
        'De bosu ligt met de platte kant naar beneden. Kom er op liggen met je buik. Vouw je handen voor je voorhoofd en strek je benen. Lift tegelijkertijd je borst en gestrekte benen van de vloer en weer terug naar de beginpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bosu_hyper_extension.png', 3),
       ('Bosu hip bridge',
        'De bosu ligt met de platte kant naar beneden. Plaats twee voeten op de bosu en je bovenlichaam op de grond. Je knieen zijn gebogen, je billen liggen dicht bij de bosu. Geef druk op je benen en lift je heupen van de vloer tot volledige strekking. Gecontroleerd laat je je heupen weer zakken totdat je zachtjes de vloer aan raakt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bosu_hip_bridge.png', 3),
       ('Bosu Crunch',
        'Ga met je onderrug tegen de bolle kant van de bosu aanzitten. Knieen gebogen, voeten dicht bij je lichaam. Kruis je handen voor je borst en trek je navel in. Kom rustig omhoog maar hou je onderrug tegen de bosu bal. Hierna zak je weer rustig naar beneden. Spanning behouden.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bosu_crunch.png', 1),
       ('Pistol squat',
        '(opbouwen door eerst de squat te doen) Pak de RIP60 met twee handen vast. Zorg dat je met gestrekte armen een klein beetje hangt in de RIP60. Je strekt 1 been naar voren en zakt door het andere been door je billen naar achter te brengen en je knie te buigen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/pistol_squat.png', 1),
       ('Glute Bridge',
        'Ga op de grond liggen met je voeten in de RIP60. Voeten op heupbreedte, zet druk op je voeten en duw je heup omhoog. Je navel is in en je buikspieren aangespannen. Bovenin span je je billen aan en houd je je bovenlijf zo recht mogelijk.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/glute_bridge.png', 4),
       ('Single arm row',
        '(opbouwen met normale Row) Pak 1 handvat van de RIP60 vast. Ga in de RIP60 hangen met een gestrekte arm. Houd je rug recht en span je buikspieren aan. Trek jezelf omhoog met de elleboog dicht langs het lichaam. Heupen blijven recht en je laat jezelf weer rustig zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/single_arm_row.png', 6),
       ('High row',
        'Pak de RIP60 met 2 handen vast. Duw je hakken in de grond en ga met gestrekte armen hangen. Zorg ervoor dat je rug recht blijft en je heup niet wegzakt. Trek jezelf omhoog met je elleboog op schouder hoogte. Je elleboog duw je licht naar buiten. Hierna ga je rustig terug naar gestrekte armen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/high_row.png', 7),
       ('Tricep push up',
        'Ga met je knieen op de grond zitten en pak de RIP60 met twee handen vast. Schouders boven polsen, vanaf schouders naar knie een rechte lijn naar beneden. Buig je ellebogen en laat je rustig zakken met je armen dicht langs het lichaam. Heupen blijven recht en je duwt jezelf weer rustig omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/tricep_push_up.png', 6),
       ('Inside chest fly''s',
        'Pak de RIP60 met twee handen vast. Zet je tenen in de grond en ga met gestrekte armen opzij hangen. Zorg ervoor dat je rug recht blijft en je heupen niet naar beneden zakken. Breng je handen met gestrekte armen naar elkaar toe. Hierna breng je ze weer rustig naar buiten, armen blijven gestrekt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/inside_chest_fly.png', 3),
       ('Standing side bend',
        'Pak de RIP60 met twee handen gestrekt vast. Ga zijwaarts staan en houdt je handen boven je hoofd. Zorg ervoor dat je zijwaarts in de RIP60 leunt. Laat nu de heup zijwaarts zakken totdat je in een soort halve maan vorm komt. Duw nu je heup terug naar de rechte startpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/standing_side_bend.png', 3),
       ('Standing cable chestpress',
        'Zet de katrollen op borsthoogte. Pak de handvatten vast en zet je armen in een hoek van 90 graden. Zet een klein stapje naar voren zodat er spanning komt op de cable. Je strekt je armen volledig uit naar voren. Bovenlichaam stil. Laat ze weer rustig terug zakken, tot de 90 graden hoek in de ellebogen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/standing_cable_chest_press.png', 7),
       ('Standing cable chest fly',
        'Zet de katrollen op borsthoogte. Pak de handvatten vast en zet met gestrekte armen een stapje naar voren zodat er spanning komt op de cable. Armen zijn zijwaarts en gestrekt. Breng de handen naar elkaar toe. Breng ze met gestrekte armen weer rustig terug. niet voorbij het lichaam laten zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/standing_cable_chest_fly.png', 7),
       ('Straight arm pulldown',
        'Begin met de katrol in de hoogste positie. Houdt je rug recht en breng met gestrekte armen de stang naar je bovenbeen. Hierna weer met gestrekte armen omhoog tot je armen langs je oren zijn.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/straigth_arm_pulldown.png', 5),
       ('Rope face pull',
        'Zet de katrol op ooghoogte. Pak het touw bovenhands vast en breng de kabel op spanning door een stapje naar achter te zetten. Trek het touw naar je toe met je handen langs je gezicht, ellebogen naar buiten en hoger dan je schouders. Strek je armen weer rustig naar voren tot gestrekte armen, gewichten van de cable raken elkaar niet.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/rope_face_pull.png', 5),
       ('Cable side raises',
        'De katrol start in de onderste positie. Je pakt het handvat met een hand vast en met je andere hand pak je de stang vast voor stabiliteit. Zet een stapje naar buiten zodat de cable op spanning staat. Beweeg je arm gestrekt omhoog tot schouderhoogte.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/cable_side_raises.png', 5),
       ('Oblique twist',
        'Stel het katrol in tussen heup en schouderhoogte. Je brengt je armen gestrekt horizontal van links naar rechts en andersom.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/oblique_twist.png', 3),
       ('Deadlift',
        'Voeten op heupbreedte, pak de stang bovenhands vast buiten je knieen, schenen staan tegen de stang. Schouders licht over de stang heen en trek je schouderbladen naar beneden met een rechte rug, borst op en kijk naar voren. Strek vanuit je knieen terwijl je een rechte rug houdt. Je armen blijven recht en de halter blijft dicht bij je schenen. De deadlift eindigt wanneer je volledig gestrekt bent en het gewicht is opgetild. Laat het gewicht weer zakken en buig hierbij je knieen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/19.jpg', 4),
       ('Bench press',
        'Ga liggen op een bankje met de voeten stevig in de vloer. Pak de stang vast net iets buiten de schouders. Buig je ellebogen en laat de stang naar beneden zakken tot borsthoogte. Ellebogen zijn licht naar buiten gekeerd. Duw hierna het gewicht weer omhoog. Je onderrug duw je in het bankjes, buikspieren zijn aangespannen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/6.jpg', 2),
       ('Front squat',
        'Plaats de stang hoog op je bovenrug (back squat) of op je sleutelbenen met je ellebogen naar voren (front squat). Voeten staan op schouderbreedte, tenen licht naar buiten. Breng je billen naar achter en buig je knieen tot je heupen op knie lijn zijn (90 graden). Duw je knieen naar buiten en duw het gewicht vanuit je hakken weer omhoog. Bovenin volledige strekking van de heup, geen overstrekking in de knie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/37.jpg', 1),
       ('Goblet squat (1 dumbbell)',
        'Ga met je voeten iets breder dan schouderbreedte staan, pak de dumbbell met twee handen vast en houd deze voor je borst. Houd je borst recht omhoog en kijk voor je uit. Laat je langzaam door je knieen zakken, alsof je gaat zitten op een stoel. Leg bij het zakken je lichaamsgewicht op je hakken. Kom parallel met de grond (hoek van 90 graden) en druk vervolgens met je hakken jezelf weer omhoog. Zorg ervoor dat je knieen niet op slot gaan wanneer je bovenin komt, wel volledige heupstrekking.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/goblet_squat.png', 1),
       ('Dumbbell Flyes (bench flat/incline)',
        'Ga zitten op een bankje en pak twee dumbbells. Zet de dumbbells op je knieen en breng je lichaam naar achter. Hierdoor kom je plat te liggen op het bankje, voeten stevig op de vloer en de dumbbells horizontal boven de schouders. Breng de gewichten rustig naar buiten, je hebt een kleine knik in je ellebogen. Dumbbells komen onder niet voorbij het lichaam. Met bijna gestrekte armen ook weer omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/dumbbell_flyes.png', 2),
       ('Dumbbell shrugs',
        'Pak in iedere hand een dumbbell, sta rechtop, voeten onder de heupen, knieen uit het slot. Armen blijven gestrekt en je trekt je schouders omhoog en laat ze weer rustig zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/dumbbell_schrugs.png', 7),
       ('Side raise',
        'Pak in iedere hand een dumbbell, sta rechtop, voeten onder de heupen, knieen uit het slot. Armen zijn gestrekt langs het lichaam. Beweeg je armen zijwaarts omhoog tot schouderhoogte. Hierna weer rustig omlaag.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/side_raise.png', 7),
       ('Hammer curl',
        'Pak in iedere hand een dumbbell, sta rechtop, voeten onder de heupen, knieen uit het slot. Armen zijn gestrekt langs het lichaam, ellebogen blijven langs het lichaam terwijl je de gewichten omhoog brengt tot schouderhoogte. Laat ze weer rustig zakken tot je armen volledig gestrekt zijn. De dumbbells blijven recht, niet indraaien.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/75.jpg', 8),
       ('Standing calf raises',
        'Voeten op heupbreedte, een dumbbell in iedere hand. Borst is rechtop, knieen licht gebogen. Ga op je tenen staan en zak weer rustig omlaag tot net boven de grond.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/standing_calf_raises.png', 1),
       ('Stiff leg deadlift (2 dumbbells)',
        'Voeten onder je heupen en knieen licht gebogen. Een dumbbell in iedere hand. Dumbbells horizontal voor je bovenbenen. Borst is rechtop en je buigt met een rechte rug vanuit je heup naar voren. Geen buiging in de knieen. Dumbbells blijven dicht bij het lichaam. Je buigt tot ongeveer kniehoogte, hierna kom je weer met dezelfde rechte rug overeind.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/stiff_leg_deadlift.png', 4),
       ('2 arm bent over dumbbell row',
        'In iedere hand een dumbbell. Voeten onder de heupen, knieen licht gebogen. Buig met een rechte rug vanuit je heup naar voren. Gewicht is dicht bij het lichaam en je trekt het langs de zijkant omhoog. Elleboog wijst naar boven. Blijf voorover staan en strek je arm weer terug naar beneden.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/2_arm_bent_over_dumbbell_row.png', 4),
       ('Bent over lateral raise',
        'Pak in iedere hand een dumbbell, voeten onder de heupen, knieen uit het slot en buig vanuit je heup naar voren met een rechte rug. Armen zijn gestrekt langs het lichaam. Beweeg je armen zijwaarts omhoog tot schouderhoogte. Hierna weer rustig omlaag.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bent_over_lateral_raise.png', 7),
       ('Seated dumbbell overhead extension',
        'Ga zitten op een bankje, voeten op de grond en bovenlichaam recht. Pak een dumbbell met twee handen vast boven je hoofd. In de beginpositie zijn de armen volledig gestrekt. Je laat het gewicht achter je hoofd zakken door je ellebogen te buigen. De ellebogen wijzen naar binnen en je armen blijven smal. Je stopt net boven je bovenrug en daarna strek je weer uit omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/seated_dumbbell_overhead_extension.png',
        7),
       ('One leg calf raises',
        'Pak een steunpunt vast met je hand. In de andere hand heb je een dumbbell. Een voet op de grond, de andere knie is gebogen. Gewicht aan de kant van de voet die op de grond staat. Je lift je hak van de grond en komt op je tenen. Hierna zak je rustig naar beneden.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/one_leg_calf_raises.png', 1),
       ('Dumbbell Lunges',
        'Pak in beide handen een dumbbell. Voeten staan onder de heupen en houd je borst rechtop. Met een voet zet je een grote stap recht naar voren. Je achterste knie breng je naar de grond. Beide benen hebben een hoek van 90 graden. Je bovenlichaam blijft recht op. Stap terug en wissel van been.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/dumbbell_lunges.png', 1),
       ('Flat dumbbell press',
        'Ga zitten op een bankje en pak twee dumbbells. Je zet de dumbbells op je knieen en je brengt je lichaam naar achter. Hierdoor kom je plat te liggen op het bankje, voeten stevig op de vloer en de dumbbells horizontal boven de schouders. Buig je ellebogen en laat de dumbbells rustig naar beneden zakken. Ellebogen duw je licht naar buiten en ze zakken niet voorbij je lichaam. Vanuit hier duw je ze weer uit omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/1.jpg', 2),
       ('One arm dumbbell row',
        'Zet het bankje plat. Zet een voet op de grond, je knie en een hand op het bankje. Zorg ervoor dat je rug recht is en span je buikspieren aan. Trek het gewicht dicht langs de zijkant van je lichaam omhoog en houd hierbij je elleboog schuin omhoog.Zorg ervoor dat je arm niet volledig gestrekt is aan het einde van de oefening.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/28.jpg', 4),
       ('Shoulder Press',
        'Ga zitten op een bankje met twee dumbbells in je handen. Je rug is recht en je buikspieren zijn aangespannen. Breng de gewichten omhoog tot een hoek van 90 graden in de ellebogen, dit is je beginpositie.Vanaf hier strek je je armen omhoog, gewichten blijven horizontal. En je laat ze weer rustig zakken tot 90 graden.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/shoulder_press.png', 7),
       ('Bicep curl',
        'Voeten onder de heupen, dumbbells horizontal voor je bovenbenen, armen gestrekt. Ellebogen zijn langs het lichaam en je buigt je ellebogen om de gewichten naar schouderhoogte te brengen. Hierna laat je de gewichten weer rustig zakken tot net voor de bovenbenen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/bicep_curl.png', 5),
       ('Lying tricep extension',
        'Ga liggen op een bankje met een dumbbell in beide handen. Strek je armen recht boven je schouders en laat de dumbbells naar elkaar toe wijzen, handpalmen naar elkaar toe. Buig je elleboog en laat het gewicht rustig naar je voorhoofd zakken tot een hoek van 90 graden. Ellebogen blijven naar binnen tijden de oefening.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/lying_tricep_extension.png', 6),
       ('Dumbbell press indraaien',
        'Ga met je rug op een horizontale bank liggen. Houd je voeten op de grond en laat je armen naar boven wijzen. Plaats je handen tegenover elkaar met de duimen naar binnen. Breng de dumbbells in een gelijkmatige beweging tot borsthoogte door je ellebogen te buigen en je onderarmen naar binnen te draaien. Druk de dumbbells weer omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/2.jpg', 2),
       ('Flys',
        'Ga liggen op een smalle bank met de voeten op de grond. Neem de dumbbells in de handen en strek je armen. Laat de dumbbells tot horizontale positie zakken. Breng de dumbbells weer omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/3.jpg', 2),
       ('Pull over',
        'Ga met je rug op de bank liggen met je voeten op de grond. Strek je armen en laat een schijf van de dumbbell op je handplamen rusten. Omklem het handvat met duimen en wijsvingers. Breng de halter achter je hoofd door eerst zo ver mogelijk te komen met gestrekte arm, het laatste stuk kunt u de arm buigen. Breng rustig weer terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/4.jpg', 2),
       ('Incline bench press',
        'Ga op de bank zitten met de rugleuning schuin tussen 45 en 60 graden. Pak de stang onderhands vast op iets meer dan schouderbreedte. Laat de barbell zakken tot aan de bovenzijde van het borstbeen. Strek de armen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/7.jpg', 2),
       ('Wellnessball press',
        'Ga liggen met de knieën in een hoek van 90 graden, waarbij je rug en schouderbladen worden ondersteund door de bal. Breng de handen met gewichten recht naar boven. Laat de armen zakken met de ellebogen naar buiten tot deze in een 90 graden hoek is. Breng de armen weer in aanvangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/8.jpg', 2),
       ('Front pull',
        'Ga rechtop staan met voeten op schouderbreedte en dumbbells in je handen met je handpalmen naar binnen. Breng 1 dumbbell met gestrekte arm schuin naar voren en omhoog totdat je hand ter hoogte is van de andere schouder. Herhaal met de andere arm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/9.jpg', 2),
       ('Lay down Front pull',
        'Ga met je rug tegen een fitnessbankje zitten op 45 graden. Zorg dat je nek en hoofd ondersteund zijn. Houd de dumbbells naast je lichaam met je handpalmen naar boven. Breng nu langzaam beide dumbbells naar voren met licht gebogen armen totdat ze voor en net boven je lichaam zijn.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/10.jpg', 2),
       ('Straight arm barbell pullover',
        'Strek je armen. Houd de halter met de duimen naar binnen vast en de handen op schouderbreedte. Laat je borstkas zo ver mogelijk omhoog komen en laat de halter achter je hoofd zakken door je armen licht te buigen. Breng je armen terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/11.jpg', 2),
       ('Wellness ball flys',
        'Ga liggen met je knieën in een hoek van 90 graden, waarbij hoofd en nek en schouderbladen worden ondersteund door de bal. Neem de dumbbells in de handen en strek je armen. Laat de dumbbells tot horizontale positie zakken. Breng de dumbbells weer omhoog terwijl u uitademt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/13.jpg', 2),
       ('Wellness ball press indraaien',
        'Ga liggen met je knieën in een hoek van 90 graden, waarbij hoofd, rug en schouderbladen worden ondersteund door de bal. Breng je handen met gewichten recht naar boven. Laat je armen zakken met je ellebogen naar buiten tot deze in een 90 graden hoek zijn. Breng de armen weer in aanvangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/14.jpg', 2),
       ('Incline flys',
        'Ga zitten op een schuine bank en omklem de halters met je handen. Laat je armen recht omhoog wijzen of buig ze licht. Laat de armen tot horizontale positie zakken. Breng de armen terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/17.jpg', 2),
       ('Incline dumbbell press',
        'Ga zitten op een schuine bank. Buig je armen en omklem de dumbbells met je duimen naar binnen. Strek je armen en breng de halters naar elkaar toe.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/18.jpg', 2),
       ('Sumo deadlift',
        'Je staat met je voeten op heupbreedte (je tenen wijzen naar buiten, maar bevinden zich altijd onder de knieën). Buig door de knieën tot je bovenbenen horizontaal zijn. Pak de halter met gestrekte armen en je duimen naar binnen vast, of de ene hand in de onderhandse greep en de andere in de bovenhandse. Maak je rug iets hol, span de buikspieren aan en strek je benen door je bovenlichaam op te richten met je schouders naar achteren.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/20.jpg', 4),
       ('Bent over row',
        'Ga met licht gebogen knieën staan, je bovenlichaam in een hoek van 45 graden naar voren, de rug goed recht. Houd de barbell met een bovenhandse greep vat op iets meer dan schouderbreedte en je armen omlaag. Houd je buikspieren aangespannen. Trek de stang op tot borsthoogte. Kom terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/21.jpg', 4),
       ('Pelvis lift',
        'Kom op de rug met de armen naast het lichaam en de knieën gebogen. Span de buikspieren aan en til langzaam de billen van de grond. Duw de voeten stevig in de grond, duw de knieën naar de muur voor je. Het hoofd moet je nog op kunnen tillen, de nek niet blokkeren. Houd de billen enkele tellen van de grond en laat de billen weer tot net boven de grond zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/22.jpg', 4),
       ('Rear delt row',
        'Buig door je knieën, pak de stang met gewichten beet op iets meer dan schouderbreedte, plaats je voeten op schouderbreedte en houd je rug goed recht. Til de barbell nu recht omhoog tot aan je borst. Laat de barbell vervolgens beheersd terugzakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/23.jpg', 4),
       ('Bent over long bar row',
        'Buig voorover en buig je knieën licht. Pak de barbell beet en en trek hem naar je toe waarbij je elleboog langs je romp blijft totdat de gewichten je romp raken. Span je rugspieren aan tijdens de oefening en houd het gewicht enkele seconden vast op het hoogste punt. Kom langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/24.jpg', 4),
       ('Good morning',
        'Ga met je voeten op heupbreedte staan en laat de halter op de monnikskapsspieren of iets lager rusten. Breng je lichaam in horizontale positie en houd je rug goed recht. Kom terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/25.jpg', 4),
       ('Mid back row',
        'Zet een fitnessbankje op een hoek van 45 graden. Ga hier tegenaan liggen met de buik tegen het bankje en je kin rustend op de bovenkant van het bankje. Neem twee dumbbells in beide handen met de handpalmen naar binnen. Trek de dumbbells langs je romp omhoog naar je lichaam toe waarbij de ellebogen achter de rug eindigen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/26.jpg', 4),
       ('Reverse fly',
        'Ga zitten met je bovenlichaam voorover tegen een fitnessbankje met een hoek van 45 graden. Neem de dumbbells in beide handen met de handpalmen naar binnen gericht. Til de armen zijwaarts met een lichte hoek in je ellebogen. Til de halters tot schouderhoogte, dan langzaam terug laten komen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/27.jpg', 4),
       ('Barbell row',
        'Ga zitten met de gewichten in je hand, de palmen naar beneden en je ellebogen naar buiten en je bovenlichaam tegen het bankje. Trek de gewichten naar je toe alsof je een omgekeerde bench press doet. Buig je ellebogen en breng je bovenarmen omhoog terwijl je de onderarmen laat hangen. Doe dit totdat het gewicht op dezelfde hoogte als je rug is.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/29.jpg', 4),
       ('Bent over dumbbell row',
        'Plaats je linkerknie en je linkerhand op het bankje. Je rechterbeen plaats je naast je op de grond. Met je rechterarm pak je in dit geval het gewicht vast en voer je de oefening uit. Om te beginnen buig je iets voorover. Pak de dumbbell van de grond en zorg voor een rechte of iets holle rug. Vanuit deze positie trek je de dumbbell naar de onderkant van je borst en weer beheersd terug (houd je handpalm naar je lichaam gericht).',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/30.jpg', 4),
       ('Wellnessball lower back',
        'Ga liggen op een wellness bal met je torso tegen de bal aan, parallel met de vloer. Neem een gewicht onder je kin. Dit is je startpositie. Kom langzaam omhoog door je middel en je onderrug te buigen. Houd enkele seconden vast op het hoogste punt en kom dan langzaam terug naar de startpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/31.jpg', 4),
       ('Upright Row',
        'Ga rechtop staan met de voeten op schouderbreedte. Houd de rug goed recht en houd de barbell in een overhandse greep tegen de dijen. Houd de handen op iets meer dan schouderbreedte. Trek de barbell omhoog tot je kin. Houd je ellebogen zo ver mogelijk uit elkaar. Breng de barbell met een gecontroleerde beweging omlaag.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/32.jpg', 4),
       ('Back extension',
        'Stel het apparaat zo in dat je onderbenen (ter hoogte van je enkels/hielen) en je heup goed ondersteund worden. Je bovenlichaam wordt niet ondersteund en moet vrij kunnen bewegen. Plaats je armen gekruisd over je borst of rug. Voor de start van de oefening moet je hele lichaam een rechte lijn vormen, zorg er dus voor dat je je rug goed recht houdt. Buig nu beheersd je bovenlichaam naar beneden totdat deze een hoek van 90 graden ten opzichte van je benen maakt. Til jezelf vervolgens weer omhoog totdat je lichaam weer in een rechte lijn is.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/33.jpg', 4),
       ('Barbell squat',
        'Pak een halter en ga met je benen op heupafstand van elkaar staan en laat de stang op de achterkant voor je schouders, net boven je schouderbladen, rusten. Buig door je knieën totdat je dijen evenwijdig zijn aan de vloer. Pauzeer even en keer dan langzaam terug naar de startpositie, terwijl je knieën gedurende de gehele beweging dezelfde richting op wijzen als je tenen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/34.jpg', 1),
       ('Sumo squat Barbell',
        'Ga met je voeten ongeveer op 2 x schouderbreedte uit elkaar staan, je tenen wijzen naar buiten. Pak vanuit die positie een tamelijk zware barbell en neem één einde hiervan op armlengte met beide handen stevig vast, zoals op de afbeelding. Trek je schouderbladen naar elkaar toe en recht je bovenlichaam. Buig door je knieën totdat je dijen evenwijdig zijn aan de vloer. Pauzeer even en keer dan langzaam terug naar de startpositie, terwijl je knieën gedurende de gehele beweging dezelfde richting op wijzen als je tenen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/35.jpg', 1),
       ('Barbell lunge',
        'Ga staan met je voeten naast elkaar en laat de halter in je nek op de monnikskapspieren rusten. Doe een grote stap naar voren, waarbij je de romp zo recht mogelijk houdt. Het naar voren geplaatste dijbeen moet horizontaal zijn. Kom terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/38.jpg', 1),
       ('Barbell lunge back',
        'Ga rechtop staan met voeten op schouderbreedte van elkaar. Houd de ellebogen naar achteren om zo een richel op de bovenkant van je rug te vormen waarop de stang kan rusten. Vanuit deze positie zet u een grote stap naar achteren met het linker of rechterbeen. Zak naar beneden tot het voorste been een hoek van 90 graden maakt (evenwijdig staat aan de vloer) en de knie van je andere been de grond net niet raakt. Keer de beweging om en zet krachtig af via het voorste been en hiel tot u weer rechtop staat. Houd de rug tijdens de oefening goed recht.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/39.jpg', 1),

       ('Overhead squat',
        'Houd het gewicht met 2 handen wijd uit elkaar boven je hoofd vast. Houd het lichaam onder spanning en je rug goed recht, buig je knieën en laat de billen achterwaarts komen zodat u zakt. Als de knieën een hoek van 90 graden maken keert u de beweging om en zet krachtig af via de hielen tot u weer rechtop staat.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/40.jpg', 1),

       ('Jump squat',
        'Kom rechtop staan met de voeten op meer dan heupbreedte. Buig je benen tot 45 graden, zwaai met beide armen van achter naar voren. Op de voorwaartse beweging van de armen spring je omhoog. Bij de landing gaan de armen weer naar achteren en begint de volgende sprong opnieuw. Span voor de sprong de buikspieren aan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/41.jpg', 1),

       ('Dumbbell squat',
        'Ga rechtop staan met twee dumbbells langs het lichaam met de handpalmen naar binnen en de voeten op schouderbreedte. Hou het hoofd gedurende de gehele oefening recht en kijk naar voren. Breng je lichaam langzaam naar beneden door de knieën te buigen. Ga door totdat je dijen parallel lopen met de vloer. Ga terug naar de uitgangspositie door omhoog te drukken met hoofdzakelijk de hiel van de voet totdat u in de uitgangspositie bent.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/42.jpg', 1),

       ('Dumbbell lunge',
        'Ga rechtop staan met twee dumbbells langs het lichaam met de handpalmen naar binnen. Stap met beide benen beurtelings in voorwaartse richting en probeer bij de landing met de gehele voet contact met de ondergrond te houden. Probeer met je knie niet de tenen te passeren. Gebruik makend van hoofdzakelijk de hiel van je voet, druk jezelf weer omhoog om terug te komen in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/43.jpg', 1),

       ('Side lunge dumbbell',
        'Ga rechtop staan met twee dumbbells langs het lichaam met de handpalmen naar binnen. Stap zijwaarts, of zijwaarts vooruit met het been dat je wilt trainen. Buig de knie, maar let op dat de knie niet de tenen mag passeren. Gebruik makend van hoofdzakelijk de hiel van de voet, druk jezelf weer omhoog om terug te komen in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/44.jpg', 1),


       ('Back lunge dumbbell',
        'Ga rechtop staan met twee dumbbells langs het lichaam met de handpalmen naar binnen. Stap met beide benen beurtelings naar achteren terwijl je je torso omlaag brengt en recht houdt. Let op dat de knie niet je tenen mag passeren. Gebruik makend van hoofdzakelijk de bal van de voet, druk jezelf weer omhoog om terug te komen in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/45.jpg', 1),

       ('Squat',
        'Kom rechtop staan met de voeten op schouderbreedte. Span de buikspieren aan, buig de benen, duw het zitvlak naar achteren (alsof je op een krukje achter je gaat zitten). Houd de rug goed uitgestrekt in een diagonale stand en strek de armen tot schouderhoogte naar voren. Kijk naar de grond en trek de kin iets naar de borst.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/46.jpg', 1),
       ('Sumo squat',
        'Kom rechtop staan op meer dan schouderbreedte. Knieën en tenen wijzen licht naar buiten. Strek je rug goed uit, buig je knieën en duw je billen naar achteren (alsof je op een krukje achter je gaat zitten). De bovenbenen maken een hoek van 90 graden ten opzichte van je onderbenen. Kijk naar de grond en trek de kin iets naar de borst.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/47.jpg', 1),
       ('Lunge',
        'Kom rechtop staan met de voeten op schouderbreedte. Maak een grote stap naar voren met het rechterbeen. Span je buikspieren aan en buig het voorste been en het achterste been totdat je een hoek van 90 graden maakt. Zet krachtig af met de voorste voet totdat je met de voorste voet weer naast de achterste staat.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/48.jpg', 1),
       ('Bosu squat',
        'Ga met twee voeten op schouderbreedte op de bosuball staan. Houd de armen recht vooruit. Houd het lichaam onder spanning en de rug goed recht, buig de knieën en laat de billen naar achteren komen zodat je zakt. Als de knieën een hoek van 90 graden maken zet je krachtig af met de hielen totdat je weer rechtop staat.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/49.jpg', 1),
       ('Calf stretch',
        'Kom rechtop staan, voeten op heupbreedte, benen licht gebogen. Duw krachtig met de hakken jezelf maximaal omhoog totdat je op de bal van de voeten staat. Houd deze positie 10 seconden vast en laat de hakken weer zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/50.jpg', 1),
       ('Calf stretch step',
        'Kom rechtop staan, voeten op heupbreedte, benen licht gebogen. Bal van de voeten op de step en duw met de hakken jezelf maximaal omhoog en laat de hakken langzaam weer zakken. Houd deze positie 10 seconden vast en laat de hakken weer zakken.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/51.jpg', 1),
       ('Step up',
        'Stap met je rechtervoet op de step, duw krachtig met het rechterbeen jezelf omhoog. Til gelijktijdig je linkerbeen op tot het bovenbeen horizontaal en in één lijn is met je heup. Linkerarm wordt gelijktijdig omhoog gebracht.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/52.jpg', 1),

       ('Superman',
        'Kom op handen en knieën, span de buikspieren aan en strek het linkerbeen naar achteren en de rechterarm naar voren. Blijf naar de grond kijken en strek je lichaam goed uit. Houd het been en de arm parallel aan de vloer.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/53.jpg', 1),
       ('Side leg raises',
        'Kom op je linkerzij, steun op de linkeronderarm, elleboog onder de schouder en de vuist in het verlengde van de elleboog. Benen liggen recht op elkaar in het verlengde van het bovenlichaam en strek beide benen goed uit. Til kangzaam het rechterbeen omhoog tot iets meer dan heuphoogte. Houd het een paar tellen vast en laat het been weer terugkomen. Duw met je onderarm je lichaam uit de schouder.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/54.jpg', 1),
       ('Front raise',
        'Ga rechtop staan met twee dumbbells in je handen en je handpalmen richting je lichaam. Je armen gestrekt omlaag voor je lichaam. Breng je rechterarm naar boven, zonder te buigen, tot je arm in een 90 graden hoek met je lichaam is. Breng weer terug naar uitgangspositie en wissel van arm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/55.jpg', 7),
       ('Dumbbell press',
        'Ga goed rechtop op een bank zitten met de dumbbells op schouderhoogte en de handpalmen naar voren wijzend. Strek de armen tot deze verticaal omhoog staan. U kunt de beweging ook staand uitvoeren of afwisselend met 1 arm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/56.jpg', 7),
       ('Arm circles',
        'Kom rechtop staan, met licht gebogen benen en aangespannen buikspieren. Strek de armen zijwaarts net even onder de schouderlijn. Maak kleine cirkels met de armen vanuit de schouders voorwaarts of achterwaarts. Maak de beweging van klein naar groot en weer terug.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/57.jpg', 7),
       ('Arnold press',
        'Ga zitten op een fitness bankje met de rug recht en ondersteund. Hou twee dumbbells in je handen op borsthoogte met de handpalmen naar het lichaam gericht en de armen naast het lichaam. Til de dumbbells boven je hoofd totdat ze gestrekt zijn, terwijl je je handen draait zodat de handpalmen van je af staan. Breng je handen weer langzaam terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/58.jpg', 7),
       ('Bent over raise',
        'Neem in beide handen een dumbbell. Buig voorover met licht gebogen knieën, terwijl je rug recht is en met je palmen naar binnen. Houd je torso naar voren, buig je armen licht, en til je armen op totdat ze parallel zijn met de vloer. Hou je armen daar enkele seconden en breng ze dan terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/59.jpg', 7),
       ('Dumbbell side raise',
        'Ga rechtop staan met twee dumbbells in je handen en je handpalmen naar elkaar toe. Je armen gestrekt omlaag voor je lichaam. Breng je beide armen tegelijkertijd omhoog zonder te buigen totdat ze in een rechte lijn met je schouders zijn. Breng langzaam terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/60.jpg', 7),
       ('Dumbbell one armed shoulder press',
        'Ga rechtop staan of ga recht zitten op een bankje. Breng een dumbbell op schouderhoogte naast je lichaam terwijl je handpalm van je af wijst. Druk de dumbbell recht omhoog totdat je arm gestrekt is. Kom rustig terug in uitgangspositie. Wissel van hand.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/61.jpg', 7),
       ('Dumbbell upright row',
        'Ga rechtop staan met een dumbbell in een hand die u iets voor je lichaam houdt met de elleboog licht gebogen. Hou de andere hand in de zij. Trek vanuit de elleboog de dumbbell langzaam zo ver mogelijk omhoog. De elleboog is dus altijd boven de bovenarm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/62.jpg', 7),
       ('Dumbbell front raise',
        'Ga rechtop staan met dumbbells in je handen met je handpalmen naar binnen toe. Hou het bovenlichaam stil, hef je armen omhoog tot op schouderhoogte. De handpalm moet op het hoogste punt naar de vloer wijzen. Een paar seconden vasthouden, dan langzaam de armen laten zakken naar de startpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/63.jpg', 7),
       ('Dumbbell side raise 90',
        'Ga staan met twee dumbbells in je handen. Hou de dumbbells voor je lichaam waarbij je armen parallel lopen met de vloer en je handpalman naar elkaar wijzen. Breng je armen omhoog zonder je ellebogen verder te buigen tot je bovenarmen in een lijn liggen met je schouders. Ga weer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/64.jpg', 7),
       ('Cable/tube front raise',
        'Kom rechtop staan met je voeten op schouderbreedte. Houd het handvat van de kabel met de linkerhand vast. Plaats de rechtervoet op de kabel met je rug er naartoe. Span de buikspieren aan, til de linkerarm iets gebogen op, houd de beweging even vast en laat de arm weer zakken tot de beginpositie. Met tube: fixeer de tube met de rechterhand op het bovenbeen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/65.jpg', 7),
       ('Cable/tube side raise',
        'Kom rechtop staan en houd de kabel of tube met twee handen aan de uiteinden vast. Plaats één voet op het midden van de kabel of tube. Span de buikspieren aan, lift beide armen zijwaarts omhoog tot net onder de schouderlijn. Laat de armen weer rustig zakken tot de beginpositie en houd de kabel of tube een beetje op spanning. Voorkom dat je de kin naar voren duwt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/66.jpg', 7),
       ('Side raise',
        'Neem een kabel of tube. Sta recht op. Ga met twee voeten op de kabel staan en neem de uiteinden daarna gekruist in beide handen. Beweeg beide handen tegelijkertijd naar buiten tot je armen in een lijn met je schouders staan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/67.jpg', 7),
       ('Lying lateral raise',
        'Ga op je zij liggen op een plat bankje. Houd een dumbbell in je bovenste arm voor je met je elleboog licht gebogen. Breng je arm naar boven tot je armen in een lijn is met je schouders.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/68.jpg', 7),

       ('Lying bent over raise',
        'Ga op de grond liggen. Til de dumbbell vanuit de beginpositie omhoog en houdt je elleboog licht gebogen. Laat de dumbbell weer beheersd zakken naar de beginpositie waarbij je je elleboog weer licht gebogen houdt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/69.jpg', 7),
       ('Seated bent over rear delt raise',
        'Zit op een bankje en houd de dumbbells in je handen, achter je kuiten. Buig voorover terwijl je rug recht is en met je palmen naar binnen. Hou je torso naar voren, buig je armen licht, en til je armen op totdat ze parallel zijn met de vloer. Hou je armen daar enkele seconden en breng ze dan terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/70.jpg', 7),
       ('Neck press',
        'Zittend op een bankje hou je een gemiddeld brede grip van de barbell aan. Til de barbell op en hou hem met gestrekte armen recht boven je nek. Kom langzaam naar beneden totdat je stang voelt op nekhoogte achter je hoofd. Breng langzaam weer terug omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/71.jpg', 7),
       ('Front press',
        'Zittend op een bankje hou je een gemiddeld brede grip van de barbell aan. Til de barbell op en hou hem met gestrekte armen recht boven je nek. Kom langzaam naar beneden totdat de stang op kinhoogte is. Breng langzaam weer terug omhoog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/72.jpg', 7),
       ('Triceps kick back',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Ga rechtop staan, plaats de rechter voet op het midden van de band. Plaats het rechterbeen achter op de bal van de voet op ongeveer 1 meter afstand, iets naar buiten. Houd in beide handen de uiteinden van de band vast en fixeer de band met de linker hand op het linker gebogen been. Het hele lichaam helt enigszins schuin naar voren, romp uitstrekken, kin iets naar de borst. Buig het rechterbeen, buig de rechterarm met de elleboog naar achter. Span de buikspieren aan en strek de rechter onderarm in verlengde van de rechter bovenarm. Het ellebooggewricht niet overstrekken, houd de bovenarm stil tijdens het strekken en buig daarna weer terug totdat er nog spanning in de band zit. Bepaal van tevoren hoe kort (strak) je de band moet vasthouden en houd tijdens de oefening de schouders laag. Variant: met 2 armen tegelijk.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/315.jpg', 5),
       ('Triceps kick front',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Kom in kleermakerszit of op een bankje zitten met de rechter bil op de band. Houd met de rechter hand 1 uiteinde van de band vast en til de rechter arm op totdat de rechter elleboog bijna boven de rechter schouder staat. Buig de rechter arm, houd met de linker hand de rechter bovenarm op de plaats. Strek de rug goed uit en houd vooral de rechter schouder laag tijdens de beweging. Span de buikspieren aan, strek de rechter onderarm in het verlengde van de bovenarm, houd de pols recht en laat de pink naar voren wijzen. Buig weer terug en houd de band nog gespannen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/316.jpg', 5),
       ('Twist (2)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Kom zitten in kleermakerszit of op een bankje. Sla de band om de heupen en fixeer met de linker hand de band op de linker heup. De band rust op de rechter bovenarm dat evenwijdig aan de grond opgetild is met de elleboog achter de rug. Rechter pols is in verlengde van de rechter onderarm en houd de schouder laag tijdens de beweging. Span de buikspieren aan en strek de rechter arm schuin links naar voren. Het bovenlichaam draait mee naar links, houd de heupen op de plaats. De beweging komt uit de taille, rustig en beheersd uitvoeren.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/317.jpg', 12),
       ('Vertical traction',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Kom in kleermakerszit of op een bankje zitten. Houd in beide handen de band vast en til de armen omhoog met de band schuin boven het voorhoofd. Span de buikspieren aan en trek met beiden armen de band zijwaarts op spanning en vervolgens omlaag tot borsthoogte. Houd het bekken stil en houd de schouders tijdens de beweging laag.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/318.jpg', 4),
       ('Pulley',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Kom rechtop zitten met de benen gestrekt voor je, de voeten geflext en iets van elkaar. Buig de benen heel iets en sla de band om de voetzolen. Houd in beide handen de uiteinden van de band vast en strek de rug uit. Span de buikspieren aan en trek de band met de ellebogen voorbij de rug naar achteren, de ellebogen bewegen vlak langs het lichaam. Houd de schouders laag tijdens de beweging en voorkom het uitstrekken van de kin. Variant: met de ellebogen wijd zijwaarts.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/319.jpg', 4),
       ('Twist (3)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Kom in kleermakerszit of op een bankje zitten met net niet gestrekte benen. Sla de band om de voetzolen en houd de voeten geflext (tenen naar de knieën). Kruis de band, fixeer met de linker hand de band op het linker bovenbeen. Strek de rug goed uit, span de buikspieren aan en trek met de rechter arm de band met de elleboog naar achter. De heupen op de plaats houden en draai vanuit de taille.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/320.jpg', 12),
       ('Tube curl',
        'Ga recht voor het apparaat of kabel staan. Houd het handvat onderhands vast (duim naar buiten). Buig je arm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/76.jpg', 8),
       ('Concentration curl',
        'Ga zitten en plaats je voeten op de grond op 20 cm wijder dan schouderbreedte. Pak de dumbbell en houd je bovenarm (ter hoogte van je triceps) tegen de binnenkant van je bovenbeen. In de beginpositie is je arm nagenoeg gestrekt. Vanuit deze positie til je de dumbbell omhoog waarbij je je elleboog zo min mogelijk beweegt. In de eindpositie wijst je handpalm naar je schouder toe. Breng de dumbbell weer beheersd terug naar de beginpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/77.jpg', 8),
       ('Hammer concentration curl',
        'Ga met licht gebogen knieën staan, met in beide handen een halter. De handpalmen wijzen naar je lichaam. Hef de onderarmen in de richting van de schouders. Houd deze oefening twee seconden vast. Laat de halters terugzakken in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/78.jpg', 8),
       ('Scott curl', 'Ga zitten of staan en laat je arm steunen tegen het kussen. Buig de armen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/79.jpg', 8),
       ('Reverse curl',
        'Ga met je voeten op heupbreedte staan en strek je armen. Omklem de halter met je duimen naar binnen. Buig de onderarmen. Breng met een gecontroleerde beweging de stang weer terug in de uitgangspositie',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/80.jpg', 8),
       ('EZ Bar curl',
        'Neem de EZ stang met onderhandse grip op schouderbreedte vast. Ga rechtop staan met je voeten op schouderbreedte. Beweeg de EZ stang omhoog naar je borst toe waarbij je je ellebogen dicht bij het lichaam houdt. Breng het gewicht zo hoog als je kan en knijp de biceps op het hoogtepunt voor 2 seconden aan. Keer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/81.jpg', 8),
       ('Closed-grip EZ Bar curl',
        'Neem de EZ stang met onderhandse grip vrij dicht bij elkaar vast. Ga rechtop staan met je voeten op schouderbreedte. Beweeg de EZ stang omhoog naar je borst toe waarbij je je ellebogen dicht bij het lichaam houdt. Breng het gewicht zo hoog als je kunt en knijp de biceps op het hoogtepunt voor 2 seconden aan. Keer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/82.jpg', 8),
       ('Two arm kick back',
        'Kom rechtop staan met je voeten op heupbreedte. Duw het zitvlak naar achter (alsof je op een krukje achter je gaat zitten) en strek je lichaam in een diagonale lijn schuin omhoog uit (squat). Buig de armen, bovenarmen naast het lichaam en onderarmen onder de ellebogen. Span de buikspieren aan en strek de armen naar achter, houd de bovenarmen op de plaats en zet de ellebogen niet op slot. Kijk naar de grond, de nek is lang en de kin iets naar de borst. Buig de armen tot de beginpositie en herhaal. Voer de beweging rustig en beheersd uit.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/83.jpg', 6),
       ('French press lying down',
        'Ga liggen op je rug met je benen gebogen en je voeten op heupbreedte uit elkaar. Pak de stang beet in een smalle greep en laat vanuit een gestrekte positie je armen zakken tot de stang net boven je hoofd is. Hiervandaan strek je de onderarmen uit tot je armen gestrekt zijn.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/84.jpg', 6),
       ('French press',
        'Ga zitten of rechtop staan met een barbell of dumbbells in je handen. Pak de stang beet in een smalle grip en laat vanuit een gestrekte positie de armen zakken tot achter je hoofd. Hiervandaan strek je de onderarmen uit tot je armen gestrekt zijn.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/85.jpg', 6),
       ('Kick back',
        'Kom rechtop staan en plaats het linkerbeen gebogen voor, met je knie boven de enkel. Strek de rug iets schuin omhoog uit, plaats de linkerhand op het linker bovenbeen en strek het rechterbeen naar achter (iets opzij). Span de buikspieren aan, buig de rechterbovenarm naast het lichaam, of elleboog iets boven de rug. Strek de rechterarm, houd de bovenarm op de plaats en zet de elleboog niet op slot. Kijk naar de grond, trek de kin iets naar de borst, de nek is lang. Buig de arm weer tot beginpositie en voer de beweging rustig en beheersd uit.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/86.jpg', 6),
       ('One arm triceps extension',
        'Ga zitten of staan en pak de dumbbell in 1 hand vast. In de beginpositie houd je de dumbbell met gestrekte arm boven je hoofd. Vanuit deze positie laat je de dumbbell zakken tot net iets achter je hoofd. Stoot de dumbbell daarna beheersd uit. Probeer bij deze oefening zo min mogelijk je ellebogen te bewegen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/87.jpg', 6),
       ('Lying triceps extension',
        'Ga horizontaal liggen en neem in elke hand een halter. Laat je armen naar boven wijzen. Buig je armen in een gelijkmatige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/88.jpg', 6),
       ('Triceps extension',
        'Ga op het bankje zitten en houd je benen op de grond op schouderbreedte. Houd de dumbbell met 2 handen vast. In de beginpositie houd je de dumbbell met gestrekte armen boven je hoofd. Vanuit deze positie laat je de dumbbell zakken tot net iets achter je hoofd. Stoot de dumbbell daarna beheersd uit. Probeer bij deze oefening zo min mogelijk je ellebogen te bewegen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/89.jpg', 6),
       ('Dipping',
        'Zet de handen op de zijkant van de bank, met de handpalmen op de bank en de vingers over de rand. Zet de hakken op de grond, zodat de benen gestrekt zijn. Houd de armen iets gebogen, de billen en de benen gaan in de richting van de grond doordat je je armen dieper buigt. Hoek elleboog 90 graden en span de buikspieren aan. Let op dat je niet in je schouders zakt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/90.jpg', 6),
       ('Reversed wrist curl',
        'Ga zitten en laat je onderarmen rust op je bovenbenen of op de bank. Omklem de halter of dumbbell met de duimen naar binnen en pols passief gebogen. Strek je polsen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/91.jpg', 9),
       ('Wrist curl',
        'Ga zitten en laat je onderarmen rust op je bovenbenen of op de bank. Pak de halter of dumbbell vast met een onderhandse greep (met de duimen naar buiten), zonder de polsspieren aan te spannen. Buig de polsen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/92.jpg', 9),
       ('Sit up',
        'Kom op je rug liggen en buig je benen. Plaats de voeten op de grond en houd de onderrug net op de grond. Plaats de vingertoppen tegen het achterhoofd, ellebogen zijwaarts, net iets voor de oren. Span de buikspieren aan en til je schouderbladen, borst en hoofd van de grond. Laat het bovenlichaam weer zakken, totdat de schouderbladen iets van de grond zijn. Zorg voor een gecontroleerde en rustige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/93.jpg', 3),
       ('Straight leg lift',
        'Kom op de rug liggen, met de armen langs het lichaam op de grond. Hoofd en schouders liggen op de grond. Span de buikspieren aan, strek de benen van de grond en til ze langzaam omhoog. De benen komen in een hoek van 90 graden ten opzichte van het lichaam. Buig de benen, raak met de voeten de grond en strek ze goed naar voren.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/94.jpg', 3),
       ('Crunches',
        'Ga op je rug liggen en breng je knieën boven je heupen totdat het een hoek van 90 graden vormt met het lichaam. Plaats je vingertoppen achter het hoofd, ellebogen zijn wijd, net voor de oren. Span je buikspieren aan, houd de onderrug op de grond en til je schouderbladen van de grond en laat het bovenlichaam weer zakken tot net boven de grond.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/95.jpg', 3),
       ('Gebogen leg lift',
        'Kom op de rug liggen met de armen langs het lichaam op de grond en trek je kin iets naar de borst. Span de buikspieren aan en strek je benen net boven de grond en breng ze gebogen tot boven de heup. Houd de onderrug goed op de grond en breng de benen weer in beginpositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/96.jpg', 3),
       ('Straight arm crunch',
        'Kom op je rug liggen en buig je benen. Plaats je voeten op de grond en houd de onderrug net op de grond. Strek je armen op wanghoogte langs je hoofd en houd de handen vast. Span de buikspieren aan en til je schouderbladen, borst en hoofd van de grond. Laat het bovenlichaam weer zakken, totdat de schouderbladen iets van de grond zijn. Zorg voor een gecontroleerde en rustige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/97.jpg', 3),
       ('Toe toucher',
        'Kom op je rug liggen en houd je armen gestrekt naast elkaar in de lucht ter hoogte van je borst. Je benen lichtgebogen omhoog met de knieën boven de heupen. Span je buikspieren aan, til je schouderbladen iets van de grond en raak met je handen bijna je voeten aan. Houd je buikspieren aangespannen en laat je lichaam weer zakken. Zorg voor een gecontroleerde en rustige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/98.jpg', 3),
       ('Hoover',
        'Kom in ligsteun op onderarmen en voorvoeten. Kijk naar de grond, span buikspieren aan en zorg dat voeten, billen, rug en nek in één lijn zijn. Adem goed door en strek kruin en hakken van elkaar.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/99.jpg', 3),
       ('Side bridge',
        'Ga op je zij liggen, steun op je onderarm, ellenboog onder de schouder en de vuist voor de elleboog. Plaats de voeten op elkaar en strek je benen van je af. Span je buikspieren aan en til de heupen op van de grond, tot in het verlengde van het bovenlichaam. Duw krachtig het lichaam uit het schoudergewricht en verleng het lichaam van kruin tot voeten.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/100.jpg', 3),
       ('Mountain climbers',
        'Kom in opdruk houding waarbij het lichaam op handen en voorvoeten rust. Span de buikspieren aan en breng de benen afwisselend kruislings onder het lichaam (met de knie naar de tegenovergestelde schouder). Blijf de buikspieren goed aanspannen en trek de kin iets naar de borst.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/101.jpg', 3),
       ('Air bike',
        'Ga op je rug liggen, plaats je vingers achter het hoofd met de ellebogen zijwaarts iets voor de oren. Breng je knieën boven je heupen, onderbenen horizontaal, hoek bovenbenen en lichaam 90 graden. Span je buikspieren aan, til het rechterschouderblad van de grond, draai naar links en strek het rechterbeen van je af. Houd deze positie even vast en wissel van been en schouderblad.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/102.jpg', 3),
       ('Twist met barbell',
        'Ga rechtop staan, met licht gebogen benen en aangespannen buikspieren. Plaats de stok op je schouders achter het hoofd. Strek je lichaam goed uit en draai in een horizontale beweging van links naar rechts en zorg dat je niet met je heupen meedraait. Voer de bewegingen gecontroleerd uit.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/103.jpg', 3),
       ('Side bend',
        'Ga met je voeten op heupbreedte staan en leg een hand achter je hoofd. In de andere heb je een halter. Maak een zijwaartse beweging met het bovenlichaam naar de kant zonder halter. Kom terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/104.jpg', 3),
       ('Side crunch',
        'Ga op je rug liggen, trek je benen in tot je voeten bijna bij je billen zijn. Laat beide benen op elkaar naar links liggen, onderrug komt net iets van de grond en schouderbladen blijven op de grond. Plaats je vingers achter het hoofd, houd de ellebogen zijwaarts net iets voor de oren. Span de buikspieren aan en til je schouderbladen een klein stukje van de grond. Blijf de buikspieren aanspannen, kom kleine stukjes omhoog en laat het lichaam weer zakken totdat de schouderbladen net iets van de grond blijven. Maak een gecontroleerde en rustige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/105.jpg', 3),
       ('Wellnessball crunch',
        'Ga op je rug liggen op de bal, plaats je voeten op heupbreedte. Plaats je vingers achter het hoofd, ellebogen zijwaarts net voor de oren. Span je buikspieren aan en til de schouderbladen op van de bal. Blijf je buikspieren aanspannen, kom met kleine stukjes omhoog en laat de schouderbladen weer tot net boven de bal zakken. Maak een gecontroleerde en rustige beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/106.jpg', 3),
       ('Wellnessball side crunch',
        'Ga op je rug liggen met je onderrug op de bal, plaats voeten op heupbreedte. Vingers achter het hoofd, ellebogen zijwaarts net voor de oren. Span je buikspieren aan en draai het rechter schouderblad van de bal naar links. Blijf buikspieren aanspannen, kom met kleine stukjes omhoog en laat je schouderbladen weer zakken tot iets boven de bal.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/107.jpg', 3),
       ('Welnessball lower abs',
        'Ga in een opdruk houding liggen met je schenen op de bal. Je lichaam in een rechte lijn en je armen recht naar beneden. Je handen plaats je iets wijder dan je schouders. Span je buikspieren aan, breng de bal naar je toe door je knieën te buigen en richting je borst te brengen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/108.jpg', 3),
       ('Wellnessball pikes',
        'Ga in een opdruk houding liggen met je schenen op de ballen, je lichaam in een rechte lijn en je armen recht naar beneden. Je handen plaats je iets wijder dan je schouders. Breng de bal naar je toe en zo hoog als je kunt door je heupen omhoog te bewegen. Je buigt je knieën niet.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/109.jpg', 3),
       ('Hip crunch',
        'Ga op je rug liggen met de armen gekruist voor je borst. Span je buikspieren aan en til hoofd en schouders van de grond. Lift je benen iets gebogen omhoog, de bovenbenen vormen een hoek van 90 graden met het lichaam. Strek je benen vanuit de heupen naar het plafond, houd je buikspieren goed aangespannen. Til je billen iets van de grond en houd de bovenbenen op de plaats. Laat je billen een klein stukje boven de grond weer zakken en zorg voor een langzame en gecontroleerde beweging.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/111.jpg', 3),
       ('Side tick',
        'Ga op de grond zitten waarbij je voeten en benen de grond niet raken en het bovenlichaam van de grond is, in een hoek van ongeveer 45 graden. Span je buikspieren goed aan en verplaats het gewicht naar de zijkant door de handen daar naartoe te brengen. Verplaats je handen daarna naar de andere kant van je lichaam en herhaal dit.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/112.jpg', 3),
       ('High pull', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/113.jpg', 10),
       ('Kettle bell', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/114.jpg', 10),
       ('Kettle bell doorstoten', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/115.jpg',
        10),
       ('Biceps', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/116.jpg', 10),
       ('Lunge biceps doorstoten', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/117.jpg',
        10),
       ('Thrusters', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/118.jpg', 10),
       ('Lunge & fly', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/119.jpg', 10),
       ('Prison push up', '', 'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/120.jpg', 10),
       ('Pull down',
        'Ga met je gezicht naar het apparaat toe zitten met je voeten op de grond. Klem je benen onder het kussen. Pak de handgrepen vast met beide handen en trek de handgrepen naar het bovenste deel van je borst terwijl je je ellebogen naar achteren brengt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/124.jpg', 4),
       ('Peck deck',
        'Ga zitten op het apparaat. Spreid je armen horizontaal en buig je ellebogen. Breng de armen zo dicht mogelijk bij elkaar.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/125.jpg', 2),
       ('Low row',
        'Ga met je gezicht naar het apparaat toe zitten. Maak met beide armen een trekbeweging naar het bovenlichaam toe, terwijl de armen naar voren, de ellebogen naar beneden en parallel aan het lichaam worden gehouden.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/126.jpg', 4),
       ('Pulley',
        'Ga zitten met je voeten tegen de pedalen en pak de handgrepen vast met je duimen naar binnen. Trek de handgreep, met de armen naar voren gericht, naar het bovenlichaam toe.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/127.jpg', 4),
       ('Leg extension',
        'Ga op het apparaat zitten en pak de handvatten vast zodat je bovenlichaam niet beweegt. Buig de knieën en plaats de voeten onder de rollen. Strek de benen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/128.jpg', 1),
       ('Lower back',
        'Ga zitten tegen de rugleuning aan, plaats je handen op de handvatten en je voeten op het voetvlak. Vanuit deze positie duw je jezelf beheersd naar achteren totdat je bovenlichaam een hoek van 90 graden maakt ten opzichte van je bovenbenen. Bij deze oefening train je je onderrugspieren.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/129.jpg', 4),
       ('Chest press',
        'Ga zitten met de handgrepen in lijn met het midden van je borst. Houd je polsen, ellebogen en schouders in een lijn en houd je rug recht tegen de stoel. Hou een lichte buiging in je ellebogen wanneer je je armen volledig uitstrekt. Breng het gewicht langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/130.jpg', 2),
       ('Vertical traction',
        'Ga zitten met je rug tegen de rugleuning. Pak de handgrepen vast en trek deze met een rechte rug, terwijl je naar voren kijkt, naar beneden richting je nek.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/131.jpg', 4),
       ('Adductor',
        'Ga op het apparaat zitten met gespreide benen. Breng de benen naar elkaar toe. Kom met een gecontroleerde beweging weer terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/132.jpg', 1),
       ('Abductor',
        'Ga op het apparaat zitten met je benen tussen de kussens. Spreid je benen zo wijd mogelijk uit elkaar. Kom met een gecontroleerde beweging weer terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/133.jpg', 1),
       ('Triceps push down',
        'Ga met je gezicht naar de pully staan, met de handen op het handvat, de ellebogen tegen het lichaam. Strek je onderarmen, zorg ervoor dat je ellebogen dicht bij je lichaam blijven.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/134.jpg', 6),
       ('Cable curl',
        'Ga met je gezicht naar het appraat staan en houd het handvat onderhands vast (duim naar buiten). Buig je arm.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/135.jpg', 8),
       ('Exorotatie onderarmen',
        'Ga rechtop staan met het aparaat naast je. Pak de handgreep vast en hou hem vast recht voor je lichaam waarbij je arm in een 90 graden hoek staat. Zorg dat je zo staat dat er al spanning op de kabel staat. Hou je elleboog tegen het lichaam aan, ook gedurende de oefening. Breng je arm richting je andere elleboog en daarna weer terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/136.jpg', 7),
       ('Endorotatie onderarmen',
        'Ga rechtop staan met het apparaat naast je. Pak de handgreep vast en hou hem vast recht voor je lichaam waarbij je arm in een 90 graden hoek staat. Zorg dat je zo staat dat er al spanning op de kabel staat. Houd je elleboog tegen je lichaam aan, ook gedurende de oefening. Draai je arm weg van je lichaam terwijl je arm een 90 graden hoek houdt. Daarna weer terug in uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/137.jpg', 7),
       ('Lat Machine trekbeweging voor',
        'Ga met je gezicht naar het appraat toe zitten met je voeten op de grond. Klem je benen onder het rolkussen. Wijs met je duimen naar binnen en plaats je handen ver uit elkaar. Trek de stang naar het bovenste deel van je borst, terwijl je je borstkas uitzet en je ellebogen naar achteren brengt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/138.jpg', 4),
       ('Seated leg curl',
        'Ga zitten op het apparaat en strek je benen. Het voetkussen zit net aan de onderkant van je kuit. Klem je bovenbenen vast en pak de handvatten beet. Buig je benen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/139.jpg', 1),
       ('Leg press',
        'Ga met je rug stevig tegen de rugleuning van het apparaat aan liggen spreid de voeten iets. Maak de veiligheidshendel los en buig de knieën zo ver mogelijk, tot de bovenbenen de borstkas raken. Breng je benen terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/140.jpg', 1),
       ('Lat Machine trekbeweging achter',
        'Ga met je gezicht naar het apparaat toe zitten met de voeten op de grond. Klem je benen onder het rolkussen. Wijs met je duimen naar binnen en plaats je handen ver uit elkaar. Trek de stand achter je hoofd langs tot in je nek door je ellebogen langs je lichaam te brengen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/141.jpg', 4),
       ('Roman chair',
        'Ga met je buik naar beneden liggen en klem je onderbenen onder het rolkussen. Je heupen rusten op het kussen. Plaats je handen achter je hoofd met je ellebogen naar buiten. Maak een rustige beweging naar boven waarbij je je rug (over) strekt. Kom langzaam terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/142.jpg', 4),
       ('Multi hip',
        'Ga met je gezicht naar het kussen staan en plaats je knie recht onder het kussen. Ga rechtop staan en houd de handgreep of stang vast. Breng je knie in een krachtige beweging omhoog. Breng daarna je knie langzaam terug in de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/143.jpg', 1),
       ('Total abdominal',
        'Ga zitten op het apparaat met je rug en benen goed ondersteund. Grijp de handgrepen vast en klem deze om je schouders. Buig de romp naar voren zodat je schouders naar je benen toe gaan. Blijf naar voren kijken tijdens de oefening.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/144.jpg', 3),
       ('Dr Wolff crunch',
        'Ga op je rug liggen op de bank en houd je handen achter je hoofd of op je borst. Zet je voeten tegen de voetsteunen. Til je schouders van de grond en breng je hoofd richting je knieën door je wervelkolom voorzichting op te rollen. Blijf omhoog kijken tijdens de oefening.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/145.jpg', 3),
       ('Dr Wolff gebogen leg lift',
        'Ga liggen op de bank waarbij je gehele bovenlichaam en hoofd worden ondersteund. Plaats je onderarmen tegen de armsteunen. Houd je benen in een rechte lijn met je bovenlichaam. Breng je benen omhoog door je knieën in een 90 graden hoek te brengen. Ga weer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/146.jpg', 3),
       ('Dr Wolff straight leg lift',
        'Ga liggen op de bank waarbij je gehele bovenlichaam en hoofd worden ondersteund. Plaats je onderarmen tegen de armsteunen. Houd je benen in een rechte lijn met je bovenlichaam. Breng je benen gestrekt omhoog door je buik aan te spannen. Breng je benen in een 90 graden hoek met je bovenlichaam. Ga weer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/147.jpg', 3),
       ('Dr Wolff side bench',
        'Ga met je zij tegen het apparaat aan staan met je voeten in de voetsteunen. Breng je handen kruislings op je borst. Strek je lichaam langzaam de tegenovergestelde richting van die waar je tegen aan staat. Ga weer langzaam terug naar de uitgangspositie.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/148.jpg', 3),
       ('Incline dumbbell press indraaien',
        'Ga zitten op een schuine bank. Buig je armen en omklem de dumbbells met je duimen naar binnen. Strek je armen en breng de halters naar elkaar toe waarbij je je handen naar binnen draait zodat je handpalmen naar elkaar toe staan.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/180.jpg', 2),
       ('Lift back (1)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band om de enkels zodanig dat je bij een achterwaartse beweging met 1 been weerstand voelt. Ga rechtop staan, reset je houding, houd je armen langs je lichaam, hel met je romp iets voorover vanuit het bekken. Span je buikspieren aan en til afwisselend je been achterwaarts omhoog met de hiel omhoog. Trek de rug niet holler, strek je lichaam goed uit en blijf de buikspieren aanspannen. Om beter in balans te blijven kun je beide armen gelijktijdig tot schouderhoogte voorwaarts optillen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/301.jpg', 11),
       ('Lift back (2)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band om de enkels zodanig dat je bij een achterwaartse beweging met 1 been weerstand voelt. Sta rechtop, reset je houding, houd je armen langs je lichaam, hel met je romp iets voorover vanuit het bekken. Span je buikspieren aan en til afwisselend, met de voet zijwaarts gedraaid, je been achterwaarts omhoog. Trek de rug niet holler, strek je lichaam goed uit en blijf de buikspieren aanspannen. Om beter in balans te blijven kun je beide armen gelijktijdig tot schouderhoogte voorwaarts optillen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/302.jpg', 11),
       ('Hamstring curl',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Houd de band om de enkels en plaats nu 1 voet op de band. Ga rechtop staan en reset je houding, breng het bovenbeen waar de band om de enkel zit, iets achter de heup. Hel iets voorover met je romp, span buikspieren aan, buig het andere been met de hiel richting zitvlak waarbij het bovenbeen iets achter de heup is. Om te beginnen herhaal deze oefening eerst 8 tot 10 keer met 1 been en wissel van been. Zorg ervoor dat je de andere heup niet opzij duwt.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/303.jpg', 11),
       ('Abduction (1)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Houd de band om de enkels, ga rechtop staan, span de buikspieren aan, plaats de handen op de heupen. Tik afwisselend met de benen zijwaarts de grond aan zover je reiken kunt. Houd het lichaamsgewicht centraal en houd het standbeen geheel in een lijn, heup, knie en enkel vormen een lijn. Zorg ervoor dat je andere heup niet naar binnen trekt, houd controle in de beweging. Zwaardere variant: til het been zijwaarts op van de grond.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/304.jpg', 1),
       ('Adduction (1)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Plaats 1 voet op de band, knoop de band eventueel iets losser. Laat de band eerst wat hoger op het andere been liggen, b.v. halverwege de kuit. Ga rechtop staan, armen zijwaarts voor het evenwicht, span de buikspieren aan. Lift het been voorwaarts omhoog, in knie en voet naar buiten uitgedraaid. Waak ervoor dat het bekken niet kantelt en strek de kruin naar het plafond.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/305.jpg', 1),
       ('Leg extension',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Plaats 1 voet op de band, band eventueel iets hoger op het andere been plaatsen. Til het bovenbeen niet te hoog op, houd het bovenbeen op de plaats, span de buik aan. Strek het onderbeen in verlengde van de knie, net niet op slot. Houd de rug recht, het bekken stil en de schouderbladen iets omlaag',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/306.jpg', 1),
       ('Abduction (2)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band om enkels of net onder de knieën en kom op de rug liggen. Strek het lichaam goed uit, het hoofd mag niet dieper dan de schouders liggen. Plaats de armen langs het lichaam en strek armen richting voeten. Buig de benen, strek de benen (niet overstrekken) boven de heupen of houd ze iets meer gebogen. Span de buikspieren en duw de benen gelijktijdig naar buiten en laat iets los, houd de spanning in de band. Let op dat de band niet te losjes geknoopt is voor de juiste spierspanning te behalen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/307.jpg', 1),
       ('Abduction (3)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band om de enkels of net onder de knieën',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/308.jpg', 1),
       ('Adduction (2)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band wat losser om enkel en voet, kom op de rechter zij liggen. De band zit onder de linker en de rechter voet. Strek het rechter been in verlengde van het lichaam en buig de rechter arm onder het hoofd. Buig het linker been over of achter het rechter been, houd het hele lichaam goed recht. Span de buikspieren aan, duw de schouderbladen iets omlaag. Til het rechter been omhoog vanuit de heup en weer iets terug, duw de band met de linkervoet op de grond en houd de heupen goed boven elkaar.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/309.jpg', 1),
       ('Leg raise',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Knoop de band om de benen net onder de knieën. Kom op handen en knieën, polsen onder de schouders handen op schouderbreedte. Knieën op heupbreedte, knieën iets achter de heupen( bovenbenen staan iets schuin). Duw het lichaam met de handen uit de schouders, span de buikspieren en trek de kin iets naar de borst. Strek het rechter been naar achter en lift het been tot iets boven de bil en laat het been weer gestrekt omlaag net boven de grond.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/310.jpg', 11),
       ('Twist (1)',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Ga rechtop staan, sla de band om de heupen en fixeer de band met de hand op de linker heup en houd de band vrij kort vast in de rechter hand. Reset je houding, span de buikspieren aan en lift en draai de linker knie iets naar binnen op, terwijl je de rechter arm naar de linker heup toe strekt (draait). Het bovenlichaam draait mee vanuit de taille, houd de heupen op de plaats en houd de buikspieren goed aangespannen. Het standbeen gestabiliseerd houden, enkel, knie en heup blijven in elkaars verlengde.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/311.jpg', 12),
       ('Side raise',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Ga rechtop staan en plaats 1 voet in het midden van de band, de andere voet op heupbreedte ernaast. Houd in beide handen de uiteinden van de band vast. Span de buikspieren aan, strek de rug goed uit. Lift beide armen tot schouderhoogte zijwaarts op, laat de armen iets gebogen. Houd de schouders laag tijdens de raise en laat de armen weer zakken tot naast de heupen. Variant: single side raise: met 1 arm zijwaarts. Variant: voor zwaardere uitvoering 2 voeten op de band.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/312.jpg', 5),
       ('Front raise',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Ga rechtop staan en plaats je linkervoet in het midden van de band, je rechtervoet iets naar achteren. Houd in beide handen de uiteinden van de band vast. Span de buikspieren aan, houd de rug goed recht. Lift beide armen voorwaarts tot schouderhoogte, blijf met de schouders boven de heupen. Houd de schouders laag tijdens de raise, hang niet achterover en laat de armen weer zakken tot net voor de bovenbenen.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/313.jpg', 5),
       ('Biceps curl',
        'Deze oefening kan ook worden uitgevoerd zonder attribuut of met een tube. Ga rechtop staan en plaats 1 of 2 voeten in het midden van de band. Pak met beide handen de uiteinden van de band vast. De armen hangen langs het lichaam, duimen en wijsvingers wijzen nog naar voren. Houd de knieën iets gebogen, span de buikspieren aan en buig de armen. Draai voor het buigen de binnenkant van onderarmen naar je toe en breng de handen richting schouders. Houd de rug recht tijdens de curl en de schouders laag. Laat de onderarmen weer zakken (net niet helemaal gestrekt).',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/314.jpg', 5),
       ('Barbell curl',
        'Ga rechtop staan, houd je rug recht en houd de halter, met de duimen naar buiten, iets verder dan schouderbreedte uit elkaar vast. Buig je armen en zorg er door middel van spanning in de bil-, buik- en rugspieren voor dat het bovenlichaam stabiel blijft.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/74.jpg', 8),
       ('Dumbbell curl',
        'Ga zitten of staan en neem in elke hand een halter en draai je handpalmen naar binnen. Buig je arm, draai de pols naar buiten voordat de onderarm horizontaal is. Hef je elleboog.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/73.jpg', 8),
       ('Roeien',
        'Ga op de roeimachine zitten en begin met roeien. Het programma start vanzelf.',
        'https://s3-eu-west-1.amazonaws.com/training-plan.maartendev.me/assets/plank_knees.png', 10);

INSERT INTO WorkshopExercise (WorkshopId, ExerciseId)
VALUES (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 7),
       (2, 8),
       (2, 9),
       (2, 10),
       (2, 11),
       (2, 12),
       (2, 13),
       (3, 14),
       (3, 15),
       (3, 16),
       (3, 17),
       (3, 18),
       (3, 19),
       (4, 20),
       (4, 21),
       (4, 22),
       (4, 23),
       (4, 24),
       (4, 25),
       (5, 26),
       (5, 27),
       (5, 28),
       (5, 29),
       (5, 30),
       (5, 31),
       (6, 32),
       (6, 33),
       (6, 34),
       (6, 35),
       (6, 36),
       (6, 37),
       (6, 38),
       (7, 39),
       (7, 40),
       (7, 41),
       (7, 42),
       (7, 43),
       (7, 44),
       (8, 45),
       (8, 46),
       (8, 47),
       (9, 48),
       (9, 49),
       (9, 50),
       (9, 51),
       (9, 52),
       (9, 53),
       (9, 54),
       (9, 55),
       (9, 56),
       (9, 57),
       (9, 58),
       (9, 59),
       (9, 60),
       (9, 61),
       (9, 62),
       (9, 63);

INSERT INTO Journeys(Name) value ('Active');

INSERT INTO JourneyWorkshop (JourneyId, WorkshopId)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9);

INSERT INTO TrainingSchedules(Name, UserId)
VALUES ('Kracht', 1);

INSERT INTO TrainingScheduleExercise (TrainingScheduleId, ExerciseId, Sets)
VALUES 
       (1, 218, '2km'),
       (1, 62, '15-15-15'),
       (1, 58, '15-15-15'),
       (1, 48, '15-15-15'),
       (1, 54, '15-15-15');