kind: Service
apiVersion: v1
metadata:
  name: training-plan-svc
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: training-plan-app
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-plan-app-deployment
  labels:
    app: training-plan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-plan-app
  template:
    metadata:
      labels:
        app: training-plan-app
    spec:
      containers:
      - name: training-plan-app
        image: $DOCKER_IMAGE_URL:$GIT_COMMIT_SHORT
        ports:
        - containerPort: 80
